Paratii-Video/paratii-portal

- package.json
- webpack.config.js
- yarn.lock
**Issue**
#11 
**Work Done**
- do not add assets as inline data urls; instead, use `file-loader` to make them available in the `build/` dir
- Change sourcemap type and only generate sourcemaps in dev/test mode
- uglify code in prod build
@jellegerbrandy do you still want to generate any kind of sourcemaps in production? If so, which from [this list](https://webpack.js.org/configuration/devtool/) do you think would be best?
> 11 |  Bundle Improvement

- package-lock.json
- package.json
- src/scripts/components/Play.js
- src/scripts/components/VideoOverlay.js
- src/scripts/reducers/PlayerReducer.js
- src/scripts/types/ApplicationTypes.js
- test/functional-tests/player.test.js
Take new `paratii-mediaplayer` version to increase load performance! Thanks @ya7ya 
I'm going to push a new version of mediaplayer and include those changes in this PR before merging. Change will be to re-enable hiding of mediaplayer controls. https://github.com/Paratii-Video/paratii-mediaplayer/pull/36
Also, fix hiding/showing of controls and play/pause controls by clicking on video overlay.
Next will include transitions for the player elements and more tests!!
> 22 - bump player version to make loading faster

- .circleci/config.yml
- .flowconfig
- src/scripts/actions/UploadActions.js
- src/scripts/components/VideoForm.js
- src/scripts/constants/ActionConstants.js
- src/scripts/containers/VideoManagerContainer.js
- src/scripts/records/VideoRecords.js
- src/scripts/reducers/VideosReducer.js
- src/scripts/waitForServer.js
- test/functional-tests/player.test.js
- test/functional-tests/uploader.spec.js
- test/unit-tests/fixtures/VideoFixtures.js
- test/unit-tests/reducers/VideosReducer.test.js
**Work Done**
- add unit tests for all actions handled by the videos reducer
- remove a reducer path that wasn't being used
- change/fix some logic in the reducers (with a focus on ensuring edge cases are covered and that the whole state remains immutable)
- add a scripts/configure circle so that chimp tests do not start until dev server is responsive
@jellegerbrandy I changed code in all of the video reducer code paths, so feel free to do some testing to make sure nothing is screwed up. I do not know the uploader as well at this point to be able to tell for sure that things are working 100% as designed. (Also I think the transcoder is still not working so difficult to test the entire workflow).
Resolves #112, #160, and #166
> 112 - video reducer unit tests (and a few other things)

- package-lock.json
- package.json
We accidentally saved a `package-lock.json` w/ an upgraded, backwards incompatible version of clappr. Fixing here
cc @jellegerbrandy
> Fix clappr dep

- src/scripts/components/Play.js
this introduces the concept of code-splitting explain https://reactjs.org/docs/code-splitting.html
This is useful to keep the initial needed code small enough.
as an exaxmple, I chose to separate the `paratii-mediaplayer` till it's needed to play a video. check out the article above and the code to get an idea of the change required.
__note__ this is also possible for webpacked libs , not just react ( `paratii-lib` ). checkout https://webpack.js.org/guides/code-splitting/ for more info.
> split mediaplayer code for lazy loading

- src/server/routes/index.js
- webpack.config.js
**Problem**
- `/embed/:id` was loading the regular portal, not the specialized embed route. And once it got there you always saw `404`
**Work Done**
- fix how embed param was passed to template
- fix embed styles processing
@geckoslair could you do some testing to make sure this is all good? My fix works at a high level but if you can make sure all of the partials are rendering as expected that would be great 😄
> Fix embed route

- src/scripts/components/Play.js
- src/scripts/types/ApplicationTypes.js
**Issue**
#345 
**Problem**
Volume always starts at `0` on page load
**Work Done**
Set volume in `redux` when player is created
**Demo**
> 345 - initialize volume correctly

- src/scripts/components/Play.js
- src/scripts/components/widgets/forms/TextareaField.js
- src/styles/app.scss
- Description height
https://github.com/paratii-video/paratii-portal/issues/354
Handling the text area height when `componentDidMount`
- Sharing overlay opacity settings (make more transparent) #359
https://github.com/Paratii-Video/paratii-portal/issues/359
@pedrocasa I've set the opacity to `0.9`
> Description height - fixed #354  - Sharing overlay opacity - solved #359

- src/scripts/components/widgets/RedeemVoucher.js
- src/scripts/containers/RedeemVoucherContainer.js
**Issue**
#366 
**Problem**
After redeeming PTI via a voucher, the balance in the nav bar does not update after either 3 minutes have passed or the user reload the page. This is not ideal!
**Work Done**
Trigger a balance update once the voucher has been redeemed. 
**Note**
~~I do not have a voucher code to test this with so if someone could send me one that would be great 😄~~
☝️ I got some vouchers, tested, and it works
> 366 - refresh token balances after voucher redemption

- src/scripts/components/Play.js
- src/scripts/components/PlayerControls.js
**Issue**
#360 
**Problem**
The seek bar never fully hid when playing a video
**Work Done**
- fully hide controls
- when playing/pausing via space bar, prevent browser from also scrolling on this key press (it led to a very bad UX)
**Demo**
cc @felipegaucho
> 360 - fully hide controls and fix player bug

- src/scripts/components/VideoList.js
- src/scripts/components/VideoManager.js
- src/scripts/constants/UIConstants.js
**Problem** 
When you have uploaded a lot of videos, your video list can grow super tall making the other activities on the upload page too tall to be usable.
***
**Fix**
Set a max height for the video manager and add scrolling to the video list
> Prevent super tall video manager

- src/scripts/components/widgets/modals/Modal.js
- src/scripts/components/widgets/modals/ModalStake.js
- src/scripts/containers/ModalStakeContainer.js
**Issue**
#366
**Work Done**
- trigger refresh balance after staking
- also fix bug w/ modal `z-index` (👇)
> 366 - refresh balance after staking (and fix bug)

- src/scripts/actions/ModalActions.js
- src/scripts/components/structures/header/MainHeader.js
- src/scripts/components/widgets/modals/Modal.js
- src/scripts/components/widgets/modals/ModalStake.js
- src/scripts/constants/ActionConstants.js
- src/scripts/containers/ModalStakeContainer.js
- src/scripts/records/ModalRecord.js
- src/scripts/reducers/ModalReducer.js
- src/scripts/types/ApplicationTypes.js
- import `ModalRecord` to `RootState`
https://github.com/Paratii-Video/paratii-portal/blob/5ad4262f7688e9ba100982de86ac322375db40c1/src/scripts/types/ApplicationTypes.js#L44
- > When the staking is "processing", the "continue" button should be disabled #388 
The [disableModal action](https://github.com/Paratii-Video/paratii-portal/blob/5ad4262f7688e9ba100982de86ac322375db40c1/src/scripts/actions/ModalActions.js#L13) changes the value of the [modalIsDisabled record](https://github.com/Paratii-Video/paratii-portal/blob/5ad4262f7688e9ba100982de86ac322375db40c1/src/scripts/records/ModalRecord.js#L12) . The ["continue" button ](https://github.com/Paratii-Video/paratii-portal/blob/5ad4262f7688e9ba100982de86ac322375db40c1/src/scripts/components/widgets/modals/ModalStake.js#L179) and …
> Disable Modal

- src/scripts/components/Play.js
**Issue**
#400 
**Problem**
The play component could accidentally render two video elements simultaneously, which led to a terrible player experience. The controls would jump around and you would hear two videos while only seeing one!
**Work Done**
Ensure all players are destroyed the moment before creating a new one.
> 400 - always destroy player before creating a new one

- src/scripts/components/PlayerControls.js
- src/scripts/utils/AppUtils.js
**Issue**
[paratii-mediaplayer#41](https://github.com/Paratii-Video/paratii-mediaplayer/issues/41)
**Problem**
We were rendering the fullscreen button in the player on twitter (and any other `iframe`), but we should hide this button when fullscreen mode is not enabled (which it is not on twitter).
**Screenshot**
cc @felipegaucho
> mediaplayer-41 - only render fullscreen button if fullscreen is enabled

- package.json
This was missing from `package.json` but used in `UserActions.js`
cc @eliawk
> Add bip39 to deps

- package.json
- src/scripts/components/Play.js
- src/scripts/constants/PlayerConstants.js
- yarn.lock
**Issue**
#382 (and related to #449, which is partially addressed by this PR).
**Problem**
We had no way of turning off autoplay for the embed player
**Work Done**
- allow disabling of autoplay via `autoplay` query param (for embed only)
- show controls until video plays (cc @pedrocasa, thoughts on this?)
**Notes**
- the default is still to autoplay if this query param is left out
- users can disable autoplay by passing in a `0` or `false`
**Demo**
> 382 - enable autoplay param

- src/scripts/actions/VideoActions.js
**Problem**
No videos are playing on staging/local. This is because the FE is expecting the video ID it gets from `paratii-js` to be present at key `_id`. However, due to what I think is a recent change in `paratii-js`, we can expect to find the id simply at key `id`. 
**Work Done**
Drop usage of `_id` in favor if `id`, and now videos play.
> Do not overwrite video id

- src/scripts/components/App.js
- src/scripts/components/Play.js
- src/scripts/components/VideoFormInfoBox.js
- src/scripts/utils/AppUtils.js
- src/server/routes/embed.js
- src/server/routes/index.js
- src/server/routes/oembed.js
**Issue**
#475 
**Problem**
We have hard-coded urls in our app that make testing embeds (and other things) on staging difficult or impossible.
**Work Done**
- remove all instances of hard-coded `portal.paratii.video` urls from our app
- add a util that gets the right url based on the environment
> 475 - remove hard-coded urls

- src/scripts/components/widgets/SearchResult.js
**Issue**
#503 
**Problem**
When clicking on a search result, we reload the entire app. Instead, we want to be more SPA-like and just load the correct route w/o a page reload. This helps many things in the UX, including the secure account flow.
cc @eliawk
> 130 - remove anchor tag in favor of react router link

- src/scripts/components/Play.js
- src/scripts/components/VideoOverlay.js
**Issue**
#449 
**Problem**
When a video played because of autoplay, the start screen would not go away
**Work Done**
Hide the start screen if the video plays for any reason (including autoplay)
> 449 - don't show start screen if we are playing for any reason

- src/scripts/actions/SearchActions.js
- src/scripts/reducers/SearchReducer.js
⚠️ DEPENDENT ON https://github.com/Paratii-Video/paratii-js/pull/226 ⚠️ 
**Issue**
#218 
**Work Done***
- update types of params passed to `.search()` call
- fix logic for paginating search results in the search reducer
> 218 - Fix paginated searching

- src/scripts/components/pages/SearchResults.js
- src/scripts/components/widgets/SearchResult.js
**Issue**
#130 
**Fixes**
- prevent text overflow in firefox
- add multi-line text ellipsis in chrome/safari (in firefox the text just stops w/ no ellipsis):
- remove scroll from search result description and search results wrapper
> 130 search UI fixes

- src/scripts/components/widgets/SearchResult.js
**Issue**
#539 
**Work Done**
- increase video duration font-size
**Screenshot**
@pedrocasa just FYI, the font-sizes in adobe are generally too small, in that if we use those pixel sizes they look much too small in a real browser. Perhaps the resolution of the adobe specs could be changed to help fix this?
> 539 - increase video duration font-size in search results

- src/scripts/components/structures/Card.js
**Issue**
#547 
**Work Done**
- load svg data url instead of having browser potentially request asset many many times
> 547 - load svg inline so that it is not requested for multiple times

- src/scripts/components/widgets/modals/ModalRestoreAccount.js
- src/scripts/types/ApplicationTypes.js
i've forgot to pass the mnemonic to check to `paratii.eth.wallet.isValidMnemonic`
> 546 - Wrong mnemonic check

- src/scripts/components/widgets/modals/Modal.js
- src/scripts/components/widgets/modals/ModalProfile.js
**Issue**
#571 
**Work Done**
- prevent user from closing username/email modal until they have entered a username
**Demo**
> 571 - require username in account flow

- src/scripts/actions/UserActions.js
**Issue**
#580 
**Work Done**
- add a delay to securing of wallet to allow "Securing wallet" notification to render
**Demo**
Previously, the initial and final notifications would render simultaneously, after a several-second delay. Now, we see one of the notifications first to let the user know we are doing some processing:
> 580 - adjust ux for securing wallet

- src/scripts/components/App.js
- src/scripts/components/Profile.js
- src/scripts/components/foundations/Text.js
- src/scripts/components/pages/MailVerify.js
- src/scripts/components/widgets/CheckIcon.js
- src/scripts/components/widgets/modals/ModalProfile.js
- src/scripts/containers/pages/MailVerifyContainer.js
- src/scripts/operators/UserOperators.js
- src/scripts/records/UserRecords.js
- webpack.config.js
⚠️ I was not able to actually get this flow to work; the gif below is using stubbed in data ⚠️ 
**NOTES**
- is it expected that when I verify my email I have to restore my account via a mnemonic? I would expect that I could just enter my password.
**Issue**
#609 
**Work Done**
- move email in profile page
- add checkmark next to verified emails
- add notification when you hit `/verify` route, on success or error
> 609 - add email verify notification and checkmark

- src/scripts/selectors/PlayerSelectors.js
- test/unit-tests/.eslintrc
- test/unit-tests/selectors/PlayerSelectors.test.js
⚠️ perhaps do not merge this yet as I haven't been able to test it in the browser, since the dev env is broken at the moment ⚠️ 
**Issue**
#589 
**Work Done**
- Enforce that the rendered current video time does not exceed the video duration. Due to rounding errors, it is possible that this number unexpectedly exceeds duration, so we needed to account for this.
> 589 player time fix

- .circleci/config.yml
**Work Done**
- allow `waitForServer` task on `CircleCI` to take up to two minutes
> Extend timeout

- config/production-client.json
This is part of enhancing the uploader experience and allows users to continue receiving updates after a reload.
> adding repo path for production client

- src/scripts/components/PlayerControls.js
**Issue**
#700 
**Work Done**
- add some padding around player progress bar so that progress indicator is never cut off
> 700 - fix time slider cutoff in player

- src/scripts/components/UserNav.js
Calling a function that will update state/props of a component can easily lead to a ton of re-renders across many components. We should avoid this at all costs 😅
> Do not reload balances on each render

- src/scripts/actions/AppActions.js
- src/scripts/actions/UserActions.js
- src/scripts/components/widgets/PTIBalance.js
- src/scripts/components/widgets/modals/ModalStake.js
- src/scripts/constants/UserConstants.js
- src/scripts/containers/widgets/modals/ModalStakeContainer.js
**Issue**
#756 
#763 
**Work Done**
- load account balance every 2 seconds
- remove polling logic from `<PTIBalance />` component and move the logic to the application itself
- update staking balance after making a stake (this balance is not updated every 2 seconds because I think this addl request is unnecessary. In general we should only have to update this balance when we explicitly make a stake on the FE)
**Demos**
👇 **balance**
☝️ resolution on the gif may not be great, but the gif is demonstrating that when we update the balance w/ `dev/faucet.js` the balance updates in the app immediately (and at worst, after 2 seconds)
👇 **total staked**
> 756 - regularly update account balance and update total staked
